#!/usr/bin/env node
/**
 * build.mjs — generate tokens.css from tokens.json, and REFUSE to do it if a colour rule broke.
 *
 *     node brand/build.mjs           # write brand/tokens.css
 *     node brand/build.mjs --check   # verify only; exit 1 on drift. Use this in CI.
 *
 * ## Why a build step for eleven colours
 *
 * Because the contrast law is the part of this identity that is easiest to break and hardest to
 * see. Gold on cream is 1.60:1 — it is not "a bit weak", it is invisible — and every brand guide
 * that states that rule in prose eventually gets ignored by someone in a hurry. Here the rule is
 * executable: `dozvoljeno` lists the pairings that are allowed and the ratio each must clear,
 * `zabranjeno` lists the one that is forbidden, and this script recomputes every one of them from
 * the hex values on every build. Change a colour by two digits and the build tells you which
 * pairing you just broke, by name, before it reaches a page.
 *
 * That is the whole reason tokens.json is the source and tokens.css is generated. Two hand-kept
 * copies of a palette are two palettes.
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const HERE = dirname(fileURLToPath(import.meta.url))
const tokens = JSON.parse(readFileSync(join(HERE, 'tokens.json'), 'utf8'))

/* ---- WCAG 2.x relative luminance, on sRGB ------------------------------- */
const channel = (c) => {
  const v = c / 255
  return v <= 0.04045 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4
}
const luminance = (hex) => {
  const h = hex.replace('#', '')
  const [r, g, b] = [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16))
  return 0.2126 * channel(r) + 0.7152 * channel(g) + 0.0722 * channel(b)
}
const contrast = (a, b) => {
  const [x, y] = [luminance(a), luminance(b)].sort((m, n) => n - m)
  return (x + 0.05) / (y + 0.05)
}

/* ---- the law ------------------------------------------------------------ */
const hex = (name) => {
  const c = tokens.boja[name]
  if (!c) throw new Error(`Unknown colour "${name}" in a rule. Colours: ${Object.keys(tokens.boja).join(', ')}`)
  return c.hex
}

const problems = []

for (const rule of tokens.dozvoljeno) {
  const r = contrast(hex(rule.ink), hex(rule.ground))
  if (r < rule.min) {
    problems.push(
      `ALLOWED PAIRING NO LONGER CLEARS ITS FLOOR\n` +
        `    ${rule.ink} on ${rule.ground} — ${r.toFixed(2)}:1, needs ${rule.min}:1\n` +
        `    ${rule.zasto}`,
    )
  }
}

for (const rule of tokens.zabranjeno) {
  const r = contrast(hex(rule.ink), hex(rule.ground))
  // A forbidden pairing that has become legible is not a pass — it means somebody changed a brand
  // colour far enough that the rule no longer describes the palette, and the guide now lies.
  if (r >= 4.5) {
    problems.push(
      `A FORBIDDEN PAIRING IS NOW LEGIBLE, WHICH MEANS THE PALETTE MOVED\n` +
        `    ${rule.ink} on ${rule.ground} — ${r.toFixed(2)}:1\n` +
        `    Re-read the rule before deleting it: "${rule.zasto}"`,
    )
  }
}

if (problems.length) {
  console.error('\n✗ brand/tokens.json breaks its own colour law:\n')
  for (const p of problems) console.error('  ' + p + '\n')
  process.exit(1)
}

/* ---- emit --------------------------------------------------------------- */
const pad = (s, n) => s + ' '.repeat(Math.max(0, n - s.length))
const stack = (f) => [`'${f.family}'`, ...f.fallback.map((x) => (x.includes(' ') ? `'${x}'` : x))].join(', ')

const lines = []
lines.push('/* GENERATED by brand/build.mjs from brand/tokens.json — do not edit.')
lines.push(' *')
lines.push(` * ${tokens.name} v${tokens.version}. Every pairing in tokens.json was re-measured when this`)
lines.push(' * file was written; the build fails rather than emit a palette that breaks its own law.')
lines.push(' */')
lines.push(':root {')

lines.push('  /* boja */')
for (const [k, v] of Object.entries(tokens.boja)) lines.push(`  ${pad(`--color-${k}:`, 22)}${v.hex};`)

lines.push('')
lines.push('  /* pismo */')
for (const k of ['prikaz', 'tijelo', 'podaci']) lines.push(`  ${pad(`--font-${k}:`, 22)}${stack(tokens.pismo[k])};`)

lines.push('')
lines.push('  /* velicine */')
for (const [k, v] of Object.entries(tokens.velicine)) lines.push(`  ${pad(`--text-${k}:`, 22)}${v.css}; /* ${v.px} */`)

lines.push('')
lines.push('  /* ritam */')
for (const [k, v] of Object.entries(tokens.ritam)) lines.push(`  ${pad(`--spacing-${k}:`, 22)}${v.css};`)

lines.push('')
lines.push('  /* pokret */')
lines.push(`  ${pad('--ease-izlaz:', 22)}${tokens.pokret['ease-izlaz']};`)
lines.push(`  ${pad('--ease-ulaz:', 22)}${tokens.pokret['ease-ulaz']};`)
lines.push('}')
lines.push('')

const css = lines.join('\n')
const out = join(HERE, 'tokens.css')

if (process.argv.includes('--check')) {
  const current = (() => { try { return readFileSync(out, 'utf8') } catch { return null } })()
  if (current !== css) {
    console.error('✗ brand/tokens.css is stale. Run: node brand/build.mjs')
    process.exit(1)
  }
  console.log(`✓ tokens.css current · ${tokens.dozvoljeno.length} pairings clear their floor · ${tokens.zabranjeno.length} forbidden pairing still forbidden`)
} else {
  writeFileSync(out, css)
  console.log(`✓ wrote brand/tokens.css`)
  console.log(`  ${tokens.dozvoljeno.length} allowed pairings re-measured, all clear:`)
  for (const r of tokens.dozvoljeno) {
    console.log(`    ${pad(`${r.ink} on ${r.ground}`, 30)} ${contrast(hex(r.ink), hex(r.ground)).toFixed(2)}:1`)
  }
  for (const r of tokens.zabranjeno) {
    console.log(`  forbidden, and still unreadable as required:`)
    console.log(`    ${pad(`${r.ink} on ${r.ground}`, 30)} ${contrast(hex(r.ink), hex(r.ground)).toFixed(2)}:1`)
  }
}
